### ISSUE TITLE
Questions about TfD inference

### ISSUE THREAD

**Issue by KzZheng** [alexa/teach#19]
Hi, I wonder whether the TfD inference will be released and how can I obtain the goal state changes as the same in the paper? Thanks!

**Comment by KzZheng** [comment]
Hi, I still face some problems. I use get_state_changes function in the utils.py. But I find this function may cause some state checking problems. Can I get the gt state changes for TfD instances?

**Comment by aishwaryap** [comment]
Hi @KzZheng we will work on releasing an official version of TfD inference shortly but in the meantime you can experiment with the following changes:

Comment out [line 142](https://github.com/alexa/teach/blob/main/src/teach/inference/inference_runner.py#L142) creating `edh_check_task` and instead create a new task by the same name following block 15 in the [data exploration notebook](https://github.com/alexa/teach/blob/main/src/teach/analysis/teach_data_exploration.ipynb) that creates `task_to_check`.

Also as there is no history to initialize for TfD, you will also need to comment out calls to [InferenceRunner._initialize_episode_replay](https://github.com/alexa/teach/blob/main/src/teach/inference/inference_runner.py#L151) and [InferenceRunner._load_edh_history_images](https://github.com/alexa/teach/blob/main/src/teach/inference/inference_runner.py#L164)

Apologies for the delayed response.

**Comment by aishwaryap** [comment]
Support for TfD inference has been formally added in commit [7ae16c849f597aaea54104eb387706a7e1303f1e](https://github.com/alexa/teach/commit/7ae16c849f597aaea54104eb387706a7e1303f1e). Closing this issue.
