### ISSUE TITLE
Tfd Files

### ISSUE THREAD

**Issue by 1996srikesh** [alexa/teach#4]
Hi @aishwaryap ,

I'm looking at the tfd.json files for each game. How come there are a different number of driver_actions_future and interactions? How do they correspond with one another? From the timestamps it looks like driver_actions_future just prunes some of the interactions.

**Comment by aishwaryap** [comment]
Hi @1996srikesh, `driver_actions_future` in TfD instances consist of all the interactions taken by the Follower/ Driver (`agent_id = 1`) which were successful (`success = 1`) whereas `interactions` additionally includes actions taken by the Commander (`agent_id = 0`) and actions attempted by either annotator that did not succeed in the original execution. If you wish to use additional information from `interactions`, time stamp is the right way to match them. Please let me know if this answers your question.
