### ISSUE TITLE
Issues about custom object properties

### ISSUE THREAD

**Issue by 594zyc** [alexa/teach#5]
Hi,

I notice that the custom property `simbotPickedUp` of the picked object is not set to 0 after placing (see [here](https://github.com/alexa/teach/blob/7f9e4cf8d27c0aaafef168e52750e90e8fbbf043/src/teach/simulators/simulator_THOR.py#L1713)). Is this a bug or intended behavior? 

Besides, I find that some custom properties are weird in `statediff` files. For example, in `images/train/2fbb46170662d917_06a8/statediff.464.9037940502167.json`, the `simbotLastParentReceptacle` and `simbotIsReceptacleOf` of object `Plate|-01.07|+01.65|-02.57` are both the object itself. How can that happen? 

Thanks

**Comment by aishwaryap** [comment]
Hi, we are aware of the issue with `simbotPickedUp` but we are currently not planning to change it before the end of the Simbot challenge public leaderboard phase. 

I will check the other issue and update here.
