### ISSUE TITLE
How are EDH instances segmented?

### ISSUE THREAD

**Issue by chanhee-luke** [alexa/teach#7]
Hello, what is the criteria for segmentation of EDH instances from sessions? 

Is it # of interactions or something else?

Thanks!

-Luke

**Comment by aishwaryap** [comment]
If the question is how do we decide where the ground truth action sequence to be predicted ends, the following criteria are considered:
1. In general the predicted action sequence starts after a dialog action, and ends at a dialog action, with at least one object interaction in between.
2. We examine object state changes that occurred as a result of this sequence and retain only EDH instances where some state change happened to some object relevant to the overall task that the session belongs to (these checks are rule based).
3. To evaluate the prediction of a model, the action sequence does not have to match exactly. We only check whether state changes to task relevant objects occurred.

Does this answer your question?
